In [1]:
from neural_net import NeuralNetwork
import numpy as np
from sklearn.model_selection import KFold
from sklearn.datasets import load_iris
from metrics import confusion_matrix, prediction_stats, accuracy, precision, recall, f1

In [2]:
dataset = load_iris()

X = dataset.data
Y = dataset.target

In [3]:
kf = KFold(n_splits=10, shuffle=True, random_state=42069)

In [4]:
NN = NeuralNetwork(max_iter=500, batch_size=10, error_threshold=0.01, learning_rate=0.01, random_state=42069)
NN.add_layer(n_neuron=4)
NN.add_layer(n_neuron=3, activation_function='relu')
NN.add_layer(n_neuron=3, activation_function='relu')
NN.add_layer(n_neuron=2, activation_function='sigmoid')
NN.add_layer(n_neuron=3)

In [5]:
i = 1
for train_idx, test_idx in kf.split(X):
    print(f'''------------------- FOLD {i} -------------------''')
    X_train, X_test = X[train_idx], X[test_idx]
    Y_train, Y_test = Y[train_idx], Y[test_idx]
    NN.fit(X_train, Y_train)
    y_pred = NN.predict(X_test)
    
    conf_matrix = confusion_matrix(Y_test, y_pred)
    print(f'Confusion Matrix:\n {conf_matrix}')
    print(f'Precision = {precision(Y_test, y_pred)}')
    print(f'Accuracy score = {accuracy(Y_test, y_pred)}')
    print(f'Recall Score = {recall(Y_test, y_pred)}')
    print(f'F1 Score = {f1(Y_test,y_pred)}\n')
    i += 1  

------------------- FOLD 1 -------------------
[[4.6 3.4 1.4 0.3]
 [4.4 2.9 1.4 0.2]
 [4.8 3.4 1.6 0.2]
 [5.4 3.4 1.7 0.2]
 [5.1 3.7 1.5 0.4]
 [4.6 3.2 1.4 0.2]
 [6.7 3.1 4.4 1.4]
 [6.7 3.  5.  1.7]
 [5.5 2.4 3.8 1.1]
 [5.4 3.  4.5 1.5]
 [6.  3.4 4.5 1.6]
 [6.5 3.  5.8 2.2]
 [6.5 3.2 5.1 2. ]
 [6.4 3.2 5.3 2.3]
 [5.9 3.  5.1 1.8]]
Confusion Matrix:
 [[0 6 0]
 [0 2 3]
 [0 0 4]]
Precision = 0.2357142857142857
Accuracy score = 0.3422222222222222
Recall Score = 0.4
F1 Score = 0.2965034965034965

------------------- FOLD 2 -------------------
[[5.1 3.5 1.4 0.2]
 [4.9 3.6 1.4 0.1]
 [5.  3.5 1.6 0.6]
 [6.9 3.1 4.9 1.5]
 [5.5 2.3 4.  1.3]
 [4.9 2.4 3.3 1. ]
 [5.  2.  3.5 1. ]
 [5.6 3.  4.5 1.5]
 [5.8 2.7 4.1 1. ]
 [5.7 2.6 3.5 1. ]
 [6.7 3.1 4.7 1.5]
 [6.1 3.  4.6 1.4]
 [6.7 3.3 5.7 2.1]
 [6.4 2.8 5.6 2.2]
 [6.7 3.1 5.6 2.4]]
Confusion Matrix:
 [[0 3 0]
 [0 5 4]
 [0 0 3]]
Precision = 0.4607142857142857
Accuracy score = 0.44
Recall Score = 0.5333333333333333
F1 Score = 0.4729411764705882

-----