In [26]:
from neural_net import NeuralNetwork
import numpy as np
from sklearn.model_selection import KFold
from sklearn.datasets import load_iris
from metrics import confusion_matrix, prediction_stats, accuracy, precision, recall, f1

In [27]:
dataset = load_iris()

X = dataset.data
Y = dataset.target

In [28]:
kf = KFold(n_splits=10, shuffle=True, random_state=42069)

In [29]:
NN = NeuralNetwork(max_iter=500, batch_size=10, error_threshold=0.01, learning_rate=0.01, random_state=100)
NN.add_layer(n_neuron=4)
NN.add_layer(n_neuron=3, activation_function='relu')
NN.add_layer(n_neuron=2, activation_function='relu')
NN.add_layer(n_neuron=2, activation_function='sigmoid')
NN.add_layer(n_neuron=3)

In [30]:
i = 1
for train_idx, test_idx in kf.split(X):
    print(f'''------------------- FOLD {i} -------------------''')
    X_train, X_test = X[train_idx], X[test_idx]
    Y_train, Y_test = Y[train_idx], Y[test_idx]
    NN.fit(X_train, Y_train)
    y_pred = NN.predict(X_test)
    
    conf_matrix = confusion_matrix(Y_test, y_pred)
    print(f'Confusion Matrix:\n {conf_matrix}')
    print(f'Precision = {precision(Y_test, y_pred)}')
    print(f'Accuracy score = {accuracy(Y_test, y_pred)}')
    print(f'Recall Score = {recall(Y_test, y_pred)}')
    print(f'F1 Score = {f1(Y_test,y_pred)}\n')
    i += 1  

------------------- FOLD 1 -------------------
Confusion Matrix:
 [[6 0 0]
 [2 0 3]
 [0 0 4]]
Precision = 0.4523809523809524
Accuracy score = 0.3422222222222222
Recall Score = 0.6666666666666666
F1 Score = 0.5367965367965368

------------------- FOLD 2 -------------------
Confusion Matrix:
 [[3 0 0]
 [5 0 4]
 [0 0 3]]
Precision = 0.1607142857142857
Accuracy score = 0.44
Recall Score = 0.4
F1 Score = 0.22909090909090907

------------------- FOLD 3 -------------------
Confusion Matrix:
 [[7 0 0]
 [1 0 2]
 [0 0 5]]
Precision = 0.6464285714285715
Accuracy score = 0.3688888888888889
Recall Score = 0.8
F1 Score = 0.7133333333333333

------------------- FOLD 4 -------------------
Confusion Matrix:
 [[5 0 0]
 [3 0 3]
 [0 0 4]]
Precision = 0.3607142857142857
Accuracy score = 0.3422222222222222
Recall Score = 0.6
F1 Score = 0.45034965034965035

------------------- FOLD 5 -------------------
Confusion Matrix:
 [[8 0 0]
 [4 0 0]
 [1 0 2]]
Precision = 0.5282051282051282
Accuracy score = 0.395555555