In [1]:
from neural_net import NeuralNetwork
import numpy as np
from sklearn.model_selection import KFold
from sklearn.datasets import load_iris
from metrics import confusion_matrix, prediction_stats, accuracy, precision, recall, f1

In [2]:
dataset = load_iris()

X = dataset.data
Y = dataset.target

In [3]:
kf = KFold(n_splits=10, shuffle=True, random_state=42069)

In [4]:
NN = NeuralNetwork(max_iter=500, batch_size=10, error_threshold=0.01, learning_rate=0.01, random_state=42069)
NN.add_layer(n_neuron=4)
NN.add_layer(n_neuron=3, activation_function='relu')
NN.add_layer(n_neuron=3, activation_function='relu')
NN.add_layer(n_neuron=2, activation_function='sigmoid')
NN.add_layer(n_neuron=3)

### Hasil Implementasi

In [5]:
i = 1
for train_idx, test_idx in kf.split(X):
    print(f'''------------------- FOLD {i} -------------------''')
    X_train, X_test = X[train_idx], X[test_idx]
    Y_train, Y_test = Y[train_idx], Y[test_idx]
    NN.fit(X_train, Y_train)
    y_pred = NN.predict(X_test)
    
    conf_matrix = confusion_matrix(Y_test, y_pred)
    print(f'Confusion Matrix:\n {conf_matrix}')
    print(f'Precision = {precision(Y_test, y_pred)}')
    print(f'Accuracy score = {accuracy(Y_test, y_pred)}')
    print(f'Recall Score = {recall(Y_test, y_pred)}')
    print(f'F1 Score = {f1(Y_test,y_pred)}\n')
    i += 1  

------------------- FOLD 1 -------------------
Confusion Matrix:
 [[0 6 0]
 [0 2 3]
 [0 0 4]]
Precision = 0.2357142857142857
Accuracy score = 0.3422222222222222
Recall Score = 0.4
F1 Score = 0.2965034965034965

------------------- FOLD 2 -------------------
Confusion Matrix:
 [[0 3 0]
 [0 5 4]
 [0 0 3]]
Precision = 0.4607142857142857
Accuracy score = 0.44
Recall Score = 0.5333333333333333
F1 Score = 0.4729411764705882

------------------- FOLD 3 -------------------
Confusion Matrix:
 [[0 7 0]
 [0 1 2]
 [0 0 5]]
Precision = 0.2630952380952381
Accuracy score = 0.3688888888888889
Recall Score = 0.4
F1 Score = 0.31414141414141405

------------------- FOLD 4 -------------------
Confusion Matrix:
 [[0 5 0]
 [0 3 3]
 [0 0 4]]
Precision = 0.30238095238095236
Accuracy score = 0.3422222222222222
Recall Score = 0.4666666666666667
F1 Score = 0.36536796536796534

------------------- FOLD 5 -------------------
Confusion Matrix:
 [[0 8 0]
 [0 4 0]
 [0 1 2]]
Precision = 0.28205128205128205
Accuracy sc

### Hasil Sklearn

In [6]:
from sklearn.neural_network import MLPClassifier
from sklearn.metrics import confusion_matrix, precision_score, accuracy_score, recall_score, f1_score

In [7]:
i = 1
for train_idx, test_idx in kf.split(X):
    print(f'''------------------- FOLD {i} -------------------''')
    X_train, X_test = X[train_idx], X[test_idx]
    Y_train, Y_test = Y[train_idx], Y[test_idx]
    NN.fit(X_train, Y_train)
    y_pred = NN.predict(X_test)
    
    conf_matrix = confusion_matrix(Y_test, y_pred)
    print(f'Confusion Matrix:\n {conf_matrix}')
    print(f'Precision = {precision_score(Y_test, y_pred, average="weighted")}')
    print(f'Accuracy score = {accuracy_score(Y_test, y_pred)}')
    print(f'Recall Score = {recall_score(Y_test, y_pred, average="weighted")}')
    print(f'F1 Score = {f1_score(Y_test,y_pred, average="weighted")}\n')
    i += 1  

------------------- FOLD 1 -------------------
Confusion Matrix:
 [[0 6 0]
 [0 1 4]
 [0 0 4]]
Precision = 0.18095238095238095
Accuracy score = 0.3333333333333333
Recall Score = 0.3333333333333333
F1 Score = 0.23333333333333334

------------------- FOLD 2 -------------------


C:\Users\fnaab\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.7_qbz5n2kfra8p0\LocalCache\local-packages\Python37\site-packages\sklearn\metrics\_classification.py:1318: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


Confusion Matrix:
 [[0 3 0]
 [0 5 4]
 [0 0 3]]
Precision = 0.4607142857142857
Accuracy score = 0.5333333333333333
Recall Score = 0.5333333333333333
F1 Score = 0.4729411764705882

------------------- FOLD 3 -------------------


C:\Users\fnaab\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.7_qbz5n2kfra8p0\LocalCache\local-packages\Python37\site-packages\sklearn\metrics\_classification.py:1318: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


Confusion Matrix:
 [[0 7 0]
 [0 1 2]
 [0 0 5]]
Precision = 0.2630952380952381
Accuracy score = 0.4
Recall Score = 0.4
F1 Score = 0.31414141414141405

------------------- FOLD 4 -------------------


C:\Users\fnaab\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.7_qbz5n2kfra8p0\LocalCache\local-packages\Python37\site-packages\sklearn\metrics\_classification.py:1318: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


Confusion Matrix:
 [[0 5 0]
 [0 3 3]
 [0 0 4]]
Precision = 0.30238095238095236
Accuracy score = 0.4666666666666667
Recall Score = 0.4666666666666667
F1 Score = 0.36536796536796534

------------------- FOLD 5 -------------------


C:\Users\fnaab\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.7_qbz5n2kfra8p0\LocalCache\local-packages\Python37\site-packages\sklearn\metrics\_classification.py:1318: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


Confusion Matrix:
 [[0 8 0]
 [0 4 0]
 [0 1 2]]
Precision = 0.28205128205128205
Accuracy score = 0.4
Recall Score = 0.4
F1 Score = 0.2854901960784314

------------------- FOLD 6 -------------------


C:\Users\fnaab\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.7_qbz5n2kfra8p0\LocalCache\local-packages\Python37\site-packages\sklearn\metrics\_classification.py:1318: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


Confusion Matrix:
 [[0 6 0]
 [0 1 2]
 [0 0 6]]
Precision = 0.32857142857142857
Accuracy score = 0.4666666666666667
Recall Score = 0.4666666666666667
F1 Score = 0.3828571428571428

------------------- FOLD 7 -------------------


C:\Users\fnaab\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.7_qbz5n2kfra8p0\LocalCache\local-packages\Python37\site-packages\sklearn\metrics\_classification.py:1318: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


Confusion Matrix:
 [[0 2 0]
 [0 5 0]
 [0 7 1]]
Precision = 0.6523809523809524
Accuracy score = 0.4
Recall Score = 0.4
F1 Score = 0.29395711500974653

------------------- FOLD 8 -------------------


C:\Users\fnaab\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.7_qbz5n2kfra8p0\LocalCache\local-packages\Python37\site-packages\sklearn\metrics\_classification.py:1318: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


Confusion Matrix:
 [[0 5 0]
 [0 2 3]
 [0 0 5]]
Precision = 0.3035714285714286
Accuracy score = 0.4666666666666667
Recall Score = 0.4666666666666667
F1 Score = 0.3675213675213675

------------------- FOLD 9 -------------------


C:\Users\fnaab\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.7_qbz5n2kfra8p0\LocalCache\local-packages\Python37\site-packages\sklearn\metrics\_classification.py:1318: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


Confusion Matrix:
 [[0 5 0]
 [0 3 2]
 [0 0 5]]
Precision = 0.3630952380952381
Accuracy score = 0.5333333333333333
Recall Score = 0.5333333333333333
F1 Score = 0.4316239316239316

------------------- FOLD 10 -------------------


C:\Users\fnaab\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.7_qbz5n2kfra8p0\LocalCache\local-packages\Python37\site-packages\sklearn\metrics\_classification.py:1318: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


Confusion Matrix:
 [[0 3 0]
 [0 5 0]
 [0 2 5]]
Precision = 0.6333333333333333
Accuracy score = 0.6666666666666666
Recall Score = 0.6666666666666666
F1 Score = 0.611111111111111



C:\Users\fnaab\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.7_qbz5n2kfra8p0\LocalCache\local-packages\Python37\site-packages\sklearn\metrics\_classification.py:1318: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


### Analisis

Baik pada hasil implementasi maupun menggunakan method yang disediakan oleh pustaka scikit-learn, hasil yang didapatkan hampir sama. Artinya, implementasi confusion matrix dan score dapat bekerja dengan baik. Sementara itu, hasil yang berbeda antara implementasi dan dari sklearn, dapat terjadi sebab fold yang digunakan untuk testing pada fold yang sama bisa saja berbeda.

Warning atau peringatan pada hasil dari sklearn, disebabkan terdapat kelas yang tidak muncul pada data test tetapi muncul pada hasil prediksi, ataupun sebaliknya.