In [1]:
from neural_net import NeuralNetwork
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.datasets import load_iris
from metrics import confusion_matrix, prediction_stats, accuracy, precision, recall, f1
from sklearn.neural_network import MLPClassifier

In [2]:
dataset = load_iris()

X = dataset.data
Y = dataset.target

In [3]:
X_train, X_test, Y_train, Y_test = train_test_split(X, Y, test_size=0.1)

In [4]:
def print_scores_and_matrix(y_true, y_pred):
    print(f'Confusion Matrix:\n {confusion_matrix(y_true, y_pred)}')
    print(f'Precision = {precision(y_true, y_pred)}')
    print(f'Accuracy score = {accuracy(y_true, y_pred)}')
    print(f'Recall Score = {recall(y_true, y_pred)}')
    print(f'F1 Score = {f1(y_true,y_pred)}')

In [5]:
NN = NeuralNetwork(max_iter=200, batch_size=10, error_threshold=0.1, learning_rate=0.1, random_state=42069)
NN.add_layer(n_neuron=4)
NN.add_layer(n_neuron=4, activation_function='relu')
NN.add_layer(n_neuron=4, activation_function='relu')
NN.add_layer(n_neuron=3)

In [6]:
NN.fit(X_train, Y_train)
y_pred = NN.predict(X_test)

In [7]:
print_scores_and_matrix(Y_test,y_pred)

Confusion Matrix:
 [[5 0 0]
 [4 0 0]
 [6 0 0]]
Precision = 0.1111111111111111
Accuracy score = 0.34222222222222226
Recall Score = 0.3333333333333333
F1 Score = 0.16666666666666666


In [8]:
clf = MLPClassifier(
    hidden_layer_sizes=(3,3),
    activation="relu", 
    solver="sgd", 
    batch_size=10, 
    learning_rate_init=0.01, 
    learning_rate="constant", 
    max_iter=500,
    random_state=42069
)

In [9]:
clf.fit(X_train, Y_train)
y_pred = clf.predict(X_test)

In [10]:
print_scores_and_matrix(Y_test,y_pred)

Confusion Matrix:
 [[5 0 0]
 [0 4 0]
 [0 2 4]]
Precision = 0.9111111111111111
Accuracy score = 0.34222222222222226
Recall Score = 0.8666666666666667
F1 Score = 0.8666666666666667
