In [1]:
from neural_net import NeuralNetwork
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.datasets import load_iris
from metrics import confusion_matrix, prediction_stats, accuracy, precision, recall, f1

In [2]:
dataset = load_iris()

X = dataset.data
Y = dataset.target

In [3]:
X_train, X_test, Y_train, Y_test = train_test_split(X, Y, test_size=0.1)

In [4]:
NN = NeuralNetwork(max_iter=200, batch_size=10, error_threshold=0.1, learning_rate=0.1, random_state=42069)
NN.add_layer(n_neuron=4)
NN.add_layer(n_neuron=4, activation_function='relu')
NN.add_layer(n_neuron=4, activation_function='relu')
NN.add_layer(n_neuron=3)

In [5]:
NN.fit(X_train, Y_train)

In [6]:
y_pred = NN.predict(X_test)

In [7]:
conf_matrix = confusion_matrix(Y_test, y_pred)

print(f'Confusion Matrix:\n {conf_matrix}')

Confusion Matrix:
 [[6 0 0]
 [5 0 0]
 [4 0 0]]


In [8]:
print(f'Precision = {precision(Y_test, y_pred)}')

Precision = 0.16000000000000003


In [9]:
print(f'Accuracy score = {accuracy(Y_test, y_pred)}')

Accuracy score = 0.3422222222222222


In [10]:
print(f'Recall Score = {recall(Y_test, y_pred)}')

Recall Score = 0.4


In [11]:
print(f'F1 Score = {f1(Y_test,y_pred)}')

F1 Score = 0.2285714285714286
