In [148]:
import pandas as pd
from neural_net import NeuralNetwork
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.datasets import load_iris
from metrics import confusion_matrix, prediction_stats, accuracy, precision, recall, f1

In [149]:
dataset = load_iris()

X = dataset.data
Y = dataset.target

In [150]:
X_train, X_test, Y_train, Y_test = train_test_split(X, Y, test_size=0.1)

In [151]:
NN = NeuralNetwork(max_iter=500, batch_size=10, error_threshold=0.01, learning_rate=0.01, random_state=42070)
NN.add_layer(n_neuron=4)
NN.add_layer(n_neuron=3, activation_function='relu')
NN.add_layer(n_neuron=2, activation_function='relu')
NN.add_layer(n_neuron=2, activation_function='sigmoid')
NN.add_layer(n_neuron=3)

In [152]:
NN.fit(X_train, Y_train)
y_pred = NN.predict(X_test)

### Hasil Implementasi

In [153]:
conf_matrix_us = confusion_matrix(Y_test, y_pred)
precision_us = precision(Y_test, y_pred)
accuracy_us = accuracy(Y_test, y_pred)
recall_us = recall(Y_test, y_pred)
f1_us = f1(Y_test,y_pred)

print(f'Confusion Matrix:\n {conf_matrix_us}')
print(f'Precision = {precision_us}')
print(f'Accuracy score = {accuracy_us}')
print(f'Recall Score = {recall_us}')
print(f'F1 Score = {f1_us}')

Confusion Matrix:
 [[6 0 0]
 [2 0 5]
 [0 0 2]]
Precision = 0.33809523809523806
Accuracy score = 0.39555555555555555
Recall Score = 0.5333333333333333
F1 Score = 0.4021164021164021


### Hasil Sklearn

In [154]:
from sklearn.metrics import confusion_matrix, precision_score, accuracy_score, recall_score, f1_score

In [155]:
conf_matrix_sklearn = confusion_matrix(Y_test, y_pred)
precision_sklearn = precision_score(Y_test, y_pred, average='weighted')
accuracy_sklearn = accuracy_score(Y_test, y_pred)
recall_sklearn = recall_score(Y_test, y_pred, average='weighted')
f1_sklearn = f1_score(Y_test,y_pred, average='weighted')

print(f'Confusion Matrix:\n {conf_matrix_sklearn}')
print(f'Precision = {precision_sklearn}')
print(f'Accuracy score = {accuracy_sklearn}')
print(f'Recall Score = {recall_sklearn}')
print(f'F1 Score = {f1_sklearn}')

Confusion Matrix:
 [[6 0 0]
 [2 0 5]
 [0 0 2]]
Precision = 0.33809523809523806
Accuracy score = 0.5333333333333333
Recall Score = 0.5333333333333333
F1 Score = 0.4021164021164021


h:\ITB Semester 6\Machine Learning\ML-IF3270\env\lib\site-packages\sklearn\metrics\_classification.py:1318: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


### Tabel Perbandingan Precission, Accuracy, Recall, dan F1 Score

In [156]:
table = pd.DataFrame(np.array([['Algoritma Dibuat', precision_us, accuracy_us, recall_us, f1_us], ['Algoritma Sklearn', precision_sklearn, accuracy_sklearn, recall_sklearn, f1_sklearn]]),
  columns=['Algoritma', 'Precission', 'Accuracy', 'Recall', 'F1'])
table

Algoritma           Precission             Accuracy  \
0   Algoritma Dibuat  0.33809523809523806  0.39555555555555555   
1  Algoritma Sklearn  0.33809523809523806   0.5333333333333333   

               Recall                  F1  
0  0.5333333333333333  0.4021164021164021  
1  0.5333333333333333  0.4021164021164021

### Analisis

Hasil yang didapat antara implementasi dan dari sklearn sama persis. Dengan demikian dapat disimpulkan implementasi yang telah dibuat cukup baik.

Warning atau peringatan pada hasil dari sklearn, disebabkan terdapat kelas yang tidak muncul pada data test tetapi muncul pada hasil prediksi, ataupun sebaliknya.